name: luanti-eventos
static_sites:
  - name: web
    github:
      repo: PabloColunga333/luanti-eventos
      branch: main
      deploy_on_push: true
    build_command: npm run build
    index_document: index.html
    error_document: 404.html
