name: luanti-eventos
static_sites:
  - name: web
    github:
      repo: PabloColunga333/luanti-eventos
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm run build
    output_dir: out
    index_document: index.html
    error_document: 404.html
    catchall_document: index.html
    routes:
      - path: /
        destination: /index.html
      - path: /*
        destination: /index.html
